sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: Lo6fIOq81j72nDx4y5iYdshyYhrRmSwtbVzpFbbL5MDQ42xJOpT3IPmwZHE4fgC9jSQnbnBJvZz/KHy6J2HNDrI2QFkfLVXTIjXH/PjquvFfnbhICvJ3F+8bCnbameeI7muf2u7oIzdIiMcGssjJYwA/rnfjg7UNS4JqeO60TMOTaS+Y1UvfAXVF6EDZZMem7O2dFeYQjhw6Ud2s7BATdgdvt62h4v+aXJ7+pE4LY1sesu8aG/jJuaWUlX6kKgVP3CQB+n5VEsdENeSehKEYP3iKuKQ/vlgD8Ldgin7QkDC+W8HfWlOdqs1CQpSVyUfYMcRZlt98khVVKXROEfZ+rpDHO58mdh6kXoqg24JRP5BNHCjk2PMOzA1VXgpRij+nCyoZ6Q1Nl1vel5ttmJmFpnFf8iURyaV1bBDN+KPIbs8Te9rla5LmoxA7qZWigXN7VQFQoa29yD5AJek72Pwwjxd2RZEfW8jIHkY39u7sTPBt8Nsaw/FH/GW9mHc+AQM/x3zzRQLdJLoRR4fGsHANkD9uK6y0GICkj4OHxvQwqTNobrJD3ZiqPciD+5ZhKTUnjOvHrsO3f06TObEc7BBY5GjOqNwblWEMa4cY6fz/P/yUGBLR7coS9uXcwoUkPEr8KX2dUkqTUKWcX1Pu5T/djYQEO6f7eH7nYWR9wop/O0A=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: V/kZOZJHy5hmRKOXQVjhBodyW2du6CWdrIaR9EBMDwDhBppbXkoXK1dqG2XklqKRc/1OZnstZE4lzoQxvR/bW6V6ubfknbZUI6DOUNRkPiHlFxued6YECRpkr6Ab8g1QBz7CUwE7BFc6ZAU5CE5ZS/raAusjz7RJwl1etkNEwNRzH674ppL8O7sg0YTm1uUudti+LtsbEQ9eRyaGzk4bjYz8Ow11J7GChIFH2UB1j5miT++aj0ygqo1L4/Cruf01pk8ru03HbY5bdoeg9tFAC3+0colnbz9uYCPEGWk27fJYNYAgp9mJhtQWteLxNZZ8/FUTHZWjx7BBOndnNDJDzcz2ydOWRAP+uzudamT0Dxeal5bRnEpCSnOhX9g9+SV6ozdt92R9UaL8PgA/AFP1IAaecDRdefLlCkriQCFqgddmj/8aYQBXcYrFqUdH93Y5PhjLrO3ZJPJlgv4B3cSl7UWxl+qK8ZPQbKYzB0AVfC8fHzlB6THqRpbEQppdxA6TOQXhIZ0Yx9ZLo7hO8xxeOeg+MJvgHeeMvkN/6h7XpTS2Od16mU+TnubBbdkYn+aJd847ZeVoXPMfo6fw5MV4vMzU/0Sn5xN7/eU9/KTF7+UcVPGHshHRL6UZAbtiXwj6PkirERHev8NuH7zHq8TW6XS4rT0lF/pcL6qcT26BjNw=
